FROM migrate/migrate:v4.19.1 AS migrate-bin

FROM alpine:3.24.1
RUN apk --no-cache add ca-certificates

COPY --from=migrate-bin /migrate /usr/local/bin/migrate

WORKDIR /

COPY ./migrations /migrations

ENTRYPOINT ["migrate"]